### ISSUE TITLE
Hace falta poder agregar un producto de tipo set equilibrium.

### ISSUE THREAD

**Issue by juanmnl07** [keylorm/lucesycolores#11]
Hace falta poder agregar un producto de tipo set equilibrium.

**Comment by juanmnl07** [comment]
Listo

**Comment by juanmnl07** [comment]
Se creo el tipo de contenido pero falta los campos y las variaciones

Tengo que aclarar unas dudas a +pchinchilla@orbelink.com

**Comment by keylorm** [comment]
Según se habló con Paula no habrán variaciones. serán productos con una sola variación.
