### ISSUE TITLE
Label de presentación de Producto

### ISSUE THREAD

**Issue by juanmnl07** [keylorm/lucesycolores#2]
Se necesita un label que especifique cual es la presentación o las presentaciones del producto. Actualmente se muestra la presenstación en combobox pero agregar el label para hacerlo mas claro para el usuario.

Es necesario tener la opción para escoger los tipos de presentaciones para los cuencos tibetanos, ya que estos pueden ser de diferente color y tamaño.

**Comment by juanmnl07** [comment]
Estos dos se van a manejar como un solo issue porque estan relacionados

**Comment by juanmnl07** [comment]
Hay un problema con este issue, hay que aclarar el manejo de los colores como si fueran productos o como variaciones

**Comment by keylorm** [comment]
Listo
