### ISSUE TITLE
Caso de Sets completos

### ISSUE THREAD

**Issue by juanmnl07** [keylorm/lucesycolores#7]
En varios productos(esencia de color, pamander, quintaesencia, entre otros) existe el set completo este no tiene variación, por lo tanto remover el label Product variations de productos set completos.

**Comment by juanmnl07** [comment]
Si es diferente al resto de los productos entonces debe de contemplarse como un producto diferente (aclararlo con +pchinchilla@orbelink.com)

**Comment by keylorm** [comment]
Ya se habló y se quedó en que todos los sets se manejaran como un tipo de producto mas con la variación de acuerdo a su contenido y sin variacion de color a excepción de los sets de equilibrium
