### ISSUE TITLE
Remover el filtrado de productos arcangeloi por color.

### ISSUE THREAD

**Issue by juanmnl07** [keylorm/lucesycolores#9]
Remover el filtrado de productos arcangeloi por color.

**Comment by juanmnl07** [comment]
Se encontro un problema al manejar filtrado para los colores porque hay productos que en su variabilidad de colores se genero uno para cada uno por lo tanto hay algunos que no aplica el filtrado (se aclarará con +pchinchilla@orbelink.com)

**Comment by keylorm** [comment]
Listo y resuelto
